IMAGE_NAME = "bento/ubuntu-20.04"
HA = 1

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("../../keys/kubespray.pub").first.strip
        s.inline = <<-SHELL
        echo "Ambiente para laboratório: haproxy" > /tmp/vagrant.txt
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    (1..HA).each do |i|
        config.vm.define "lb-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 90}"
            node.vm.network "forwarded_port", guest: 80, host: 80
            node.vm.network "forwarded_port", guest: 81, host: 81
            node.vm.hostname = "lb-#{i}"

            node.vm.provider :virtualbox do |v|
                v.name    = "lb-#{i}"
                v.memory = 3096
                v.cpus = 2
            end
        end
    end
end