IMAGE_NAME = "bento/ubuntu-20.04"
NODE = 2
CP = 1
ETCD = 1
RR = 1

Vagrant.configure("2") do |config|

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("../../keys/kubespray.pub").first.strip
        s.inline = <<-SHELL
        echo "Ambiente para laboratório: K8S com kubespray" > /tmp/vagrant.txt
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 3048
        v.cpus = 2
    end

    (1..NODE).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 20}"
            node.vm.hostname = "k8s-node"
            node.vm.provider :virtualbox do |v|
                v.name    = "k8s-node-#{i}"
            end
        end
    end
   

    (1..CP).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            master.vm.hostname = "k8s-master-#{i}"
            master.vm.provider :virtualbox do |v|
                v.name    = "k8s-master-#{i}"
            end
        end
    end


    (1..ETCD).each do |i|
        config.vm.define "etcd-#{i}" do |etcd|
            etcd.vm.box = IMAGE_NAME
            etcd.vm.network "private_network", ip: "192.168.50.#{i + 30}"
            etcd.vm.hostname = "k8s-etcd-#{i}"
            etcd.vm.provider :virtualbox do |v|
                v.name    = "k8s-etcd-#{i}"
            end

        end
    end
  

    (1..RR).each do |i|
        config.vm.define "calico-#{i}" do |calico|
            calico.vm.box = IMAGE_NAME
            calico.vm.network "private_network", ip: "192.168.50.#{i + 40}"
            calico.vm.hostname = "k8s-calico-#{i}"
            calico.vm.provider :virtualbox do |v|
                v.name    = "k8s-calico-#{i}"
            end

        end
    end
end