IMAGE_NAME = "bento/ubuntu-20.04"
N = 1
M = 2
E = 1
C = 1
L = 1

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("../../keys/kubespray.pub").first.strip
        s.inline = <<-SHELL
        echo "Ambiente para laboratório: K8S com kubespray" > /tmp/vagrant.txt
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 3096
        v.cpus = 2
    end

    (1..N).each do |i|
        config.vm.define "node" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.20"
            node.vm.hostname = "k8s-node"

            node.vm.provider :virtualbox do |v|
                v.name    = "k8s-node-#{i}"
            end
    
        end
    end
   

    (1..M).each do |i|
        config.vm.define "master-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "k8s-master-#{i}"


            node.vm.provider :virtualbox do |v|
                v.name    = "k8s-master-#{i}"
            end

        end
    end


    (1..E).each do |i|
        config.vm.define "etcd" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.30"
            node.vm.hostname = "k8s-etcd-1"

            node.vm.provider :virtualbox do |v|
                v.name    = "k8s-etcd-#{i}"
            end

        end
    end
  

    (1..C).each do |i|
        config.vm.define "calico" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 40}"
            node.vm.hostname = "k8s-calico-1"

            node.vm.provider :virtualbox do |v|
                v.name    = "k8s-calico-#{i}"
            end

        end
    end

end