all:

  hosts:
    k8s-lab-etcd-1:
      ansible_host: 192.168.50.30
      ip: 192.168.50.30
      access_ip: 192.168.50.30
    k8s-lab-master-1:
      ansible_host: 192.168.50.11
      ip: 192.168.50.11
      access_ip: 192.168.50.11
    k8s-lab-master-2:
      ansible_host: 192.168.50.12
      ip: 192.168.50.12
      access_ip: 192.168.50.12
    k8s-lab-node-1:
      ansible_host: 192.168.50.20
      ip: 192.168.50.20
      access_ip: 192.168.50.20
    k8s-lab-rr-1:
      ansible_host: 192.168.50.41
      ip: 192.168.50.41
      access_ip: 192.168.50.41

  children:
    kube-master:
      hosts:
        k8s-lab-master-1:
        k8s-lab-master-2:
    kube-node:
      hosts:
        k8s-lab-master-1:
        k8s-lab-master-2:
        k8s-lab-node-1:
    etcd:
      hosts:
        k8s-lab-etcd-1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
        calico-rr:
    calico-rr:
      hosts: 
        k8s-lab-rr-1:

  vars: 
    cluster_id: "1.0.0.1"
    ansible_ssh_private_key_file: ~/.ssh/kubespray